### ISSUE TITLE
Http don't work anymore

### ISSUE THREAD

**Issue by jcubic** [idevelop/ascii-camera#5]
Camera don't work anymore for http in Chrome/Chromium. You can fix it by adding message and link to use https.

The link in duck duck go for the website link to http version.

**Comment by idevelop** [comment]
@jcubic I fixed this a while ago and afaict have updated all links to be https already. Do you know of any that is still http? I wasn't aware that duck duck go hasn't yet updated their index, I'll check if there's any way to ask them to reindex. Since I host on GitHub, I don't think I have access to return a 301 redirect on the http URL.

**Comment by jcubic** [comment]
You can create a banner, hide it by default and show it when `location.protocol == "http:"`

**Comment by idevelop** [comment]
Well at that point I could just as well force redirect to https, which is not a bad idea at all but it still doesn't solve the issue of being wrongly indexed. I'll put in a redirect today. Thanks for flagging!

**Comment by idevelop** [comment]
Done. Thanks again!
